blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^category/(?P<category_slug>[\w-]+)/$',
        views.post_by_category, name='post_by_category'),
    url(r'^tag/(?P<tag_slug>[\w-]+)/$', views.post_by_tag, name='post_by_tag'),
    url(r'^(?P<id>\d+)/(?P<post_slug>[\w\d-]+)$',
        views.post_detail, name='post_detail'),
    url(r'^$', views.post_list, name='post_list'),
    url(r'^feedback/$', views.feedback, name='feedback'),
    url(r'^cookie/$', views.test_cookie, name='cookie'),
    url(r'^stop-tracking/$', views.stop_tracking, name='stop_tracking'),
    url(r'^track_user/$', views.track_user, name='track_user'),
    url(r'^test-delete/$', views.test_delete, name='test_delete'),
    url(r'^test-session/$', views.test_session, name='test_session'),
    url(r'^save-session-data/$', views.save_session_data, name='save_session_data'),
    url(r'^access-session-data/$', views.access_session_data,
        name='access_session_data'),
    url(r'^delete-session-data/$', views.delete_session_data,
        name='delete_session_data'),
    url(r'^lousy-login/$', views.lousy_login, name='lousy_login'),
    url(r'^lousy-secret/$', views.lousy_secret, name='lousy_secret'),
    url(r'^lousy-logout/$', views.lousy_logout, name='lousy_logout'),
    url(r'^login/$', views.login, name='blog_login'),
    url(r'^logout/$', views.logout, name='blog_logout'),
    url(r'^admin_page/$', views.admin_page, name='admin_page'),

]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from blog import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    url(r'^cadmin/', include('cadmin.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


# Create your models here.


class Author(models.Model):
    name = models.CharField(max_length=100, unique=True,
                            verbose_name="Author Name")
    email = models.EmailField(unique=True)
    active = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    last_logged_in = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name + "  :  " + self.email


class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

    def get_absolute_url(self):
        return reverse("post_by_category", args={self.slug})


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('post_by_tag', args=[self.slug])


class Post(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True,
                            help_text="Slug will be generated automatically from the title of the post")
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        'Author',
        on_delete=models.CASCADE,
    )
    category = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
    )
    tags = models.ManyToManyField(Tag)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('post_detail', args=[self.id, self.slug])


class Feedback(models.Model):
    name = models.CharField(max_length=200, help_text="Name of the sender")
    email = models.EmailField(max_length=200)
    subject = models.CharField(max_length=200)
    message = models.TextField(blank=False)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Feedback"

    def __str__(self):
        return self.name + "-" + self.email

blog/forms.py
from dataclasses import fields
from django import forms
from django.core.exceptions import ValidationError
from .models import Author, Tag, Category, Post, Feedback
from django.template.defaultfilters import slugify


class AuthorForm(forms.Form):
    class Meta:
        model = Author
        fields = '__all__'

    def clean_name(self):
        name = self.cleaned_data['name']
        name_l = name.lower()
        if name_l == "admin" or name_l == "author":
            raise ValidationError("Author name can't be 'admin/author'")
        return name_l

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = Author.objects.filter(email=email)
        if r.count:
            raise ValidationError("{0} already exists".format(email))
        return email.lower()


class TagForm(forms.ModelForm):

    class Meta:
        model = Tag
        fields = '__all__'

    def clean_name(self):
        n = self.cleaned_data['name']
        if n.lower() == 'tag' or n.lower() == "add" or n.lower() == "update":
            raise ValidationError("Tag name can't be '{}'".format(n))
        return n

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()


class CategoryForm(forms.ModelForm):

    class Meta:
        model = Category
        fields = '__all__'

    def clean_name(self):
        n = self.cleaned_data['name']
        if n.lower() == "tag" or n.lower() == "add" or n.lower() == "update":
            raise ValidationError("Category name can't be '{}'".format(n))
        return n

    def clean_slug(self):
        return self.cleaned_data['slug'].lower()


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'content', 'author', 'category', 'tags',)

    def clean_name(self):
        n = self.cleaned_data['title']
        if n.lower() == "post" or n.lower() == "add" or n.lower() == "update":
            raise ValidationError("Post name can't be '{}'".format(n))
        return n

    def clean(self):
        cleaned_data = super(PostForm, self).clean()
        title = cleaned_data.get('title')
        if title:
            cleaned_data['slug'] = slugify(title)
        return cleaned_data


class FeedbackForm(forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'

blog/views.py
from django.http import HttpResponse, HttpResponsePermanentRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from .models import Author, Tag, Category, Post
from django.http import HttpResponse, HttpResponseNotFound, Http404,  HttpResponseRedirect
from .forms import FeedbackForm
from django.contrib import messages
from django.core.mail import mail_admins
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django_project import helpers
from django.contrib import messages
from django.contrib import auth


def index(request):
    return HttpResponse("Hello Django")


def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 5)

    # get the page parameter from the query string
    # if page parameter is available get() method will return empty string ''
    page = request.GET.get('page')

    try:
        # create Page object for the given page
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page parameter in the query string is not available, return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if the value of the page parameter exceeds num_pages then return the last page
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post_list.html', {'posts': posts})


def post_detail(request, id, post_slug):
    post = get_object_or_404(Post, id=id)
    return render(request, 'blog/post_detail.html', {'post': post})


def post_by_category(request, category_slug):
    category = get_object_or_404(Category, slug=category_slug)
    posts = get_list_or_404(Post, category=category)
    paginator = Paginator(posts, 5)

    # get the page parameter from the query string
    # if page parameter is available get() method will return empty string ''
    page = request.GET.get('page')

    try:
        # create Page object for the given page
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page parameter in the query string is not available, return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if the value of the page parameter exceeds num_pages then return the last page
        posts = paginator.page(paginator.num_pages)
    context = {
        'category': category,
        'posts': posts
    }
    print(category)
    return render(request, 'blog/post_by_category.html', context)


def post_by_tag(request, tag_slug):
    tag = get_object_or_404(Tag, slug=tag_slug)
    posts = get_list_or_404(Post, tags=tag)
    paginator = Paginator(posts, 5)

    # get the page parameter from the query string
    # if page parameter is available get() method will return empty string ''
    page = request.GET.get('page')

    try:
        # create Page object for the given page
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page parameter in the query string is not available, return the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if the value of the page parameter exceeds num_pages then return the last page
        posts = paginator.page(paginator.num_pages)
    context = {
        'tag': tag,
        'posts': posts
    }
    return render(request, 'blog/post_by_tag.html', context)


def test_redirect(request):
    return redirect('post_list', permanent=True)


def feedback(request):
    if request.method == 'POST':
        f = FeedbackForm(request.POST)

        if f.is_valid():
            name = f.cleaned_data['name']
            sender = f.cleaned_data['email']
            subject = "You have a new Feedback from {}:{}".format(name, sender)
            message = "Subject: {}\n\nMessage: {}".format(
                f.cleaned_data['subject'], f.cleaned_data['message'])
            mail_admins(subject, message)

            f.save()
            messages.add_message(request, messages.INFO, 'Feedback Submitted.')
            return redirect('feedback')

    else:
        f = FeedbackForm()
    return render(request, 'blog/feedback.html', {'form': f})


def test_cookie(request):
    if not request.COOKIES.get('color'):
        response = HttpResponse("Cookie set")
        response.set_cookie('color', 'blue')
        return response
    else:
        return HttpResponse("Your favorite color is {0}".format(request.COOKIES['color']))


def track_user(request):
    response = render(request, 'blog/track_user.html')
    if not request.COOKIES.get('visits'):
        response.set_cookie('visits', '1', 3600 * 24 * 365 * 2)
    else:
        visits = int(request.COOKIES.get('visits', '1')) + 1
        response.set_cookie('visits', str(visits),  3600 * 24 * 365 * 2)
    return response


def stop_tracking(request):
    if request.COOKIES.get('visits'):
        response = HttpResponse("Cookies Cleared")
        response.delete_cookie("visits")
    else:
        response = HttpResponse("We are not tracking you")
    return response


def test_session(request):
    request.session.set_test_cookie()
    return HttpResponse("Testing session cookie")


def test_delete(request):
    if request.session.test_cookie_worked():
        request.session.delete_test_cookie()
        response = HttpResponse("Cookie test passed")
    else:
        response = HttpResponse("Cookie test failed")
    return response


def save_session_data(request):
    # set new data
    request.session['id'] = 1
    request.session['name'] = 'root'
    request.session['password'] = 'rootpass'
    return HttpResponse("Session Data Saved")


def access_session_data(request):
    response = ""
    if request.session.get('id'):
        response += "Id : {0} <br>".format(request.session.get('id'))
    if request.session.get('name'):
        response += "Name : {0} <br>".format(request.session.get('name'))
    if request.session.get('password'):
        response += "Password : {0} <br>".format(
            request.session.get('password'))

    if not response:
        return HttpResponse("No session data")
    else:
        return HttpResponse(response)


def delete_session_data(request):
    try:
        del request.session['id']
        del request.session['name']
        del request.session['password']
    except KeyError:
        pass

    return HttpResponse("Session Data cleared")


def lousy_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        if username == "root" and password == "pass":
            request.session['logged_in'] = True
            return redirect('lousy_secret')
        else:
            messages.error(request, 'Error wrong username/password')
    return render(request, 'blog/lousy_login.html')


def lousy_secret(request):
    if not request.session.get("logged_in"):
        return redirect("lousy_login")
    return render(request, "blog/lousy_secret_page.html")


def lousy_logout(request):
    try:
        del request.session['logged_in']
    except KeyError:
        return redirect('lousy_login')
    return render(request, 'blog/lousy_logout.html')


def login(request):
    if request.user.is_authenticated:
        return redirect('admin_page')

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = auth.authenticate(username=username, password=password)

        if user is not None:
            # correct username and password login the user
            auth.login(request, user)
            return redirect('admin_page')

        else:
            messages.error(request, 'Error wrong username/password')

    return render(request, 'blog/login.html')


def logout(request):
    auth.logout(request)
    return render(request, 'blog/logout.html')


def admin_page(request):
    if not request.user.is_authenticated:
        return redirect('blog_login')

    return render(request, 'blog/admin_page.html')

blog/templates/blog/admin_page.html
{% extends "blog/base.html" %} {% block title %} Blog - {{ block.super }}
{%endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <p>Welcome {{ request.user.username }} !</p>

    <p>User Details:</p>

    <ul>
      <li>Email: {{ request.user.username.email|default:"NA" }}</li>
      <li>SuperUser: {{ request.user.is_superuser }}</li>
      <li>Staff: {{ request.user.is_staff }}</li>
      <li>Date Joined: {{ request.user.date_joined }}</li>
      <li>Last Login: {{ request.user.last_login }}</li>
    </ul>

    <p><a href="{% url 'blog_logout' %}">Logout</a></p>
  </div>
</div>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>{% block title %}The Great Django Blog{% endblock %}</title>
    <link
      rel="stylesheet"
      href="https://fonts.googleapis.com/css?family=Open+Sans"
    />
    {% load static %}
    <link rel="stylesheet" href="{% static 'blog/css/reset.css' %}" />
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}" />
    <script src="{% static 'blog/js/jquery.js' %}"></script>
  </head>
  <body>
    <div class="navbar">
      <div class="section-inner clearfix">
        <nav>
          <a href="#">Home</a>
          <a href="#">blog</a>
          <a href="#">Contact</a>
          <a href="#">Career</a>
        </nav>
      </div>
    </div>

    {% block content %} {% endblock %} {% block footer %}

    <div class="footer">
      <div class="section-inner clearfix">
        <hr />
        <p>&copy;The great Django Footer</p>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

blog/templates/blog/feedback.html
{% extends "blog/base.html" %} {% block title %} Feedback - {{ block.super }}
{%endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <h3>Submit Your feedback</h3>

    <form action="" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td><label for="id_name">Name</label></td>
          <td><input type="text" id="id_name" name="name" /></td>
        </tr>
        <tr>
          <td><label for="id_email">Email</label></td>
          <td><input type="email" id="id_email" name="email" /></td>
        </tr>
        <tr>
          <td><label for="id_subject">Subject</label></td>
          <td><input type="text" id="id_subject" name="subject" /></td>
        </tr>
        <tr>
          <td><label for="id_message">Message</label></td>
          <td>
            <textarea
              id="id_message"
              cols="50"
              rows="10"
              name="message"
            ></textarea>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" value="Submit" /></td>
        </tr>
      </table>
    </form>
  </div>
</div>
{% endblock %}

blog/templates/blog/login.html
{% extends "blog/base.html" %} {% block title %} Blog - {{ block.super }}
{%endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <h3>Login Form</h3>

    {% if messages %}
    <ul>
      {% for message in messages %}
      <li>{{ message }}</li>
      {% endfor %}
    </ul>
    {% endif %}

    <form action="" method="post">
      {% csrf_token %}
      <table>
        <tr>
          <td><label for="id_username">Enter username</label></td>
          <td><input type="text" id="id_username" name="username" /></td>
        </tr>
        <tr>
          <td><label for="id_username">Enter password</label></td>
          <td><input type="password" id="id_password" name="password" /></td>
        </tr>
        <tr>
          <td></td>
          <td><input type="submit" value="Submit" /></td>
        </tr>
      </table>
    </form>
  </div>
</div>

{% endblock %}

blog/templates/blog/logout.html
{% extends "blog/base.html" %} {% block title %} Blog - {{ block.super }}
{%endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <p>
      You are logged out. <a href="{% url 'blog_login' %}">Click here</a> to
      login again.
    </p>
  </div>
</div>

{% endblock %}

blog/templates/blog/lousy_login.html
{% extends "blog/base.html"  %}

{% block title %}
    Lousy Login - {{ block.super }}
{% endblock %}

{% block content %}

    <div class="content">
        <div class="section-inner clearfix">

        <h3>Login Form</h3>

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <form action="" method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <td><label for="id_username">Enter Username</label></td>
                    <td><input type="text" id="id_username" name="username"></td>
                </tr>
                <tr>
                    <td><label for="id_password">Enter Password</label></td>
                    <td><input type="text" id="id_password" name="password"></td>
                </tr>
                <tr>
                    <td></td>
                    <td><input type="submit" name="submit" value="Submit"></td>
                </tr>
            </table>
        </form>

        </div>
    </div>

{% endblock %}

blog/templates/blog/lousy_logout.html
{% extends "blog/base.html" %} {% block title %} Blog - {{ block.super }}
{%endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <p>
      You have been logged out click
      <a href="{% url 'lousy_login' %}">here</a> to login again
    </p>
  </div>
</div>

{% endblock %}

blog/templates/blog/lousy_secret_page.html
{% extends "blog/base.html" %} {% block title %} Lousy Secret Page - {{
block.super }} {% endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    {% if request.session.logged_in %}
    <p>
      Welcome to the lousy secret page. You are seeing this page because you are
      logged in.
    </p>

    <p>To logout click <a href="{% url 'lousy_logout' %}">here</a></p>
    {% endif %}
  </div>
</div>

{% endblock %}

blog/templates/blog/post_by_category.html
{% extends "blog/base.html" %} {% block title %} {{ category|title }} - {{
block.super }} {% endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <h4>All the posts under category - {{ category.name }}</h4>

    {% for post in posts %}
    <h3>
      <a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
    </h3>
    <p class="post-info">{% include 'blog/post_info.html' %}</p>
    {% empty %}
    <p>There are not posts under {{ category }}</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

blog/templates/blog/post_by_tag.html
{% extends "blog/base.html" %} {% block title %} {{ tag|title }} - {{
block.super }} {% endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <h4>All the posts tagged with - {{ tag.name }}</h4>

    {% for post in posts %}
    <h3>
      <a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
    </h3>
    <p class="post-info">{% include 'blog/post_info.html' %}</p>
    {% empty %}
    <p>There are not posts tagged with {{ tag }}</p>
    {% endfor %}
  </div>
</div>
<div class="pagination">
  <div class="section-inner clearfix">
    <p>
      {% if posts.has_previous %}
      <a href="?page={{ posts.previous_page_number }}">&lt; Prev</a> | {% endif
      %} {% if posts.has_next %}
      <a href="?page={{ posts.next_page_number }}">Next &gt;</a>
      {% endif %}

      <span>Page {{ posts.number }} of {{ posts.paginator.num_pages }}</span>
    </p>
  </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends "blog/base.html" %} {% block title %} {{ post.title|capfirst }} - {{
block.super }} {% endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    <h1>{{ post.title|capfirst }}</h1>
    <p class="post-info">{% include 'blog/post_info.html' %}</p>
    | <span><a href="{% url 'post_update' post.id  %}">Edit</a></span>

    <p>{{ post.content }}</p>
  </div>
</div>

{% endblock %}

blog/templates/blog/post_info.html
<span>{{post.pub_date|date:"d M y h:i a"}}</span> |
<span
  >Category:
  <a href="{{ post.category.get_absolute_url }}">{{ post.category }}</a></span
>
<span
  >Tag: {%for tag in post.tags.all%}
  <a href="{% url 'post_by_tag' tag.slug %}">{{ tag }}"></a>
  {% empty %} None {% endfor %}
</span>

blog/templates/blog/post_list.html
{%extends "blog/base.html"%}
{%block title%}
    Blogg - {{block.super}}
{%endblock%}

{%block content%}
    <div class="content">
        <div class="section-inner clearfix">
            {%for post in posts%}
                <h3>
                    <a href="{{ post.get_absolute_url }}">{{ post.title|capfirst }}</a>
                </h3>
                <p class="post-info">
                    {% include 'blog/post_info.html' %}
                </p>    
                    {%empty%}
                        None
                    {%endfor%}
                    </span>                           
                </p>
            {% comment %} {%empty%}
                <p>There are no posts</p>
            {%endfor%}         {% endcomment %}
        </div>
    </div>
    <div class="pagination">
        <div class="section-inner clearfix">
            <p>
                {% if posts.has_previous %}
                    <a href="?page={{ posts.previous_page_number }}">&lt; Prev</a> |
                {% endif %}
    
                {% if posts.has_next %}
                    <a href="?page={{ posts.next_page_number }}">Next &gt;</a>
                {% endif %}
    
                <span>Page {{ posts.number }} of {{ posts.paginator.num_pages }}</span>
            </p>
        </div>
    </div>
{%  endblock  %}    

blog/templates/blog/track_user.html
{% extends "blog/base.html" %} {% block title %} Tracking User - {{ block.super
}} {% endblock %} {% block content %}

<div class="content">
  <div class="section-inner clearfix">
    {% if not request.COOKIES.visits %}
    <p>
      This is your first visit to the site. From now on I will track your visits
      to this site.
    </p>
    {% else %}
    <p>This is your {{ request.COOKIES.visits|add:'1' }} visit</p>
    {% endif %}

    <a href="{% url 'stop_tracking' %}">Stop Tracking Me</a>
  </div>
</div>

{% endblock %}